### ISSUE TITLE
Emby statistics 2.0.2.0 doesn't work with emby server 3.2.70.0

### ISSUE THREAD

**Issue by valkhyr1** [mregni/statistics-for-emby-server#44]
After upgrading the emby server windows to version 3.2.70.0, emby statistics 2.0.2.0 gives a error when the task is started.

 

2018-01-19 16:40:36.317 Error TaskManager: Error
    *** Error Report ***
    Version: 3.2.70.0
    Command line: C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
    Operating system: Microsoft Windows NT 6.2.9200.0
    64-Bit OS: True
    64-Bit Process: True
    User Interactive: True
    Processor count: 4
    Program data path: C:\Users\Administrator\AppData\Roaming\Emby-Server
    Application directory: C:\Users\Administrator\AppData\Roaming\Emby-Server\system
    System.MissingMethodException: Method not found: 'MediaBrowser.Controller.Entities.UserItemData MediaBrowser.Controller.Library.IUserDataManager.GetUserData(MediaBrowser.Controller.Entities.IHasUserData, MediaBrowser.Controller.Entities.IHasUserData)'.
     at Statistics.Helpers.Calculator.<CalculateLastSeenMovies>b__5_0(Movie m)
     at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
     at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
     at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count, Int32 minIdx, Int32 maxIdx)
     at System.Linq.OrderedEnumerable`1.ToList(Int32 minIdx, Int32 maxIdx)
     at System.Linq.OrderedPartition`1.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Statistics.Helpers.Calculator.CalculateLastSeenMovies()
     at Statistics.ScheduledTasks.CalculateStatsTask.<>c__DisplayClass20_1.<MediaBrowser.Model.Tasks.IScheduledTask.Execute>b__0()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
    --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Statistics.ScheduledTasks.CalculateStatsTask.<MediaBrowser-Model-Tasks-IScheduledTask-Execute>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.<ExecuteInternal>d__68.MoveNext()
    System.MissingMethodException
     at Statistics.Helpers.Calculator.<CalculateLastSeenMovies>b__5_0(Movie m)
     at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
     at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
     at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count, Int32 minIdx, Int32 maxIdx)
     at System.Linq.OrderedEnumerable`1.ToList(Int32 minIdx, Int32 maxIdx)
     at System.Linq.OrderedPartition`1.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Statistics.Helpers.Calculator.CalculateLastSeenMovies()
     at Statistics.ScheduledTasks.CalculateStatsTask.<>c__DisplayClass20_1.<MediaBrowser.Model.Tasks.IScheduledTask.Execute>b__0()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
    --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Statistics.ScheduledTasks.CalculateStatsTask.<MediaBrowser-Model-Tasks-IScheduledTask-Execute>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.<ExecuteInternal>d__68.MoveNext()
    
2018-01-19 16:40:36.318 Info TaskManager: Calculate statistics for all users Failed after 0 minute(s) and 1 seconds

**Comment by valkhyr1** [comment]
With the version 2.0.3.0 it work again ;-)
